apiVersion: v1
kind: PersistentVolume        # menentukan jenis objek yang akan dibuat, yaitu sebuah PersistentVolume
metadata:
  name: mongo-pv              # memberikan nama PersistentVolume
  labels:
    app: mongo
spec:
  capacity:                   # menyatakan kapasitas storage yang akan disediakan oleh PersistentVolume 
    storage: 1Gi              # menentukan kapasitas storage yang akan disediakan oleh PersistentVolume
  accessModes:                # menyatakan mode akses yang akan disediakan oleh PersistentVolume
    - ReadWriteOnce           # PersistentVolume(PV) tersebut tidak dapat digunakan bersama-sama oleh lebih dari satu pod, dan hanya satu pod yang dapat menulis data ke dalam PV tersebut
  hostPath:                   
    path: /data/mongo         # menentukan path di host yang akan digunakan oleh PersistentVolume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
