apiVersion: apps/v1
kind: StatefulSet           # menentukan jenis objek yang akan dibuat, yaitu sebuah StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend
  serviceName: mongo-service    # menentukan nama Service yang akan digunakan oleh StatefulSet
  replicas: 1
  minReadySeconds: 10
  template:                     # menyatakan template yang akan digunakan oleh StatefulSet untuk membuat pod
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:4.4.1
        name: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE                 # memberikan nama pada environment variable.
            value: /etc/mongo-credentials/MONGO_ROOT_USERNAME     # menyatakan sumber dari nilai environment variable
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongo 
        volumeMounts:                           # menyatakan volume yang akan digunakan oleh pod
        - name: mongo-persistent-storage
          mountPath: /data/db                   # menentukan tempat dimana volume akan di-mount
        - name: mongo-configmap
          mountPath: /config
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-config
        configMap:
          name: mongo-config
          items: 
            - key: mongo.conf
              path: mongo.conf
      - name: mongo-secret
        secret:
          secretName: mongo-secret