apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongo
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true