apiVersion: v1
kind: ConfigMap           # menentukan jenis objek yang akan dibuat, yaitu sebuah ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongo
data:                     # menyimpan data yang akan disimpan dalam ConfigMap
  # config menentukan tempat dimana volume akan di-mount
  mongo.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true