apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==