apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongo
data:
  mongo.conf: |
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    net:
      bindIp: 0.0.0.0
