apiVersion: v1        
kind: Secret          # menentukan jenis objek yang akan dibuat, yaitu sebuah Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
type: Opaque          # menentukan tipe Secret, yaitu "Opaque" yang menyimpan data dengan tipe yang tidak diketahui
data:                 # menyimpan data yang akan disimpan dalam Secret
  MONGO_ROOT_USERNAME: YWRtaW4=                           #  menyimpan username root dalam bentuk base64 encoding
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==       #  menyimpan password root dalam bentuk base64 encoding