version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run unit tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: sh build_push_image_karsajobs.sh

workflows:
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
