version: 2.1

orbs:
  hadolint: orbies/hadolint@1.0.0

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
      - auth:
          username: algozo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run unit tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build and push image
          command: |
            echo $GITHUB_TOKEN | docker login ghcr.io -u rudani37 --password-stdin
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest ghcr.io/rudani37/karsajobs:latest
            docker push ghcr.io/rudani37/karsajobs:latest

workflows:
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
