version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run unit tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    machine:
      - image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Build and push image
          command: |
            echo $GITHUB_TOKEN | docker login ghcr.io -u rudani37 --password-stdin
            docker build -t karsajobs-ui:latest .
            docker push karsajobs-ui:latest


workflows:
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
