version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    working_directory: app/
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk add build-base
      - run:
          name: Run unit tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    machine:
      image: ubuntu-1804:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: sh build_push_image_karsajobs.sh

workflows:
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
