apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  labels:
    app: karsajobs
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32767
  selector:
    app: karsajobs
