apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    app: karsajobs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/rudani37/karsajobs:latest
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "27017"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: mongo-secret
                    key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mongo-secret
                    key: MONGO_INITDB_ROOT_PASSWORD