apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31767
  selector:
    app: karsajobs-ui
