apiVersion: v1
kind: Service               # menentukan jenis objek yang akan dibuat, yaitu sebuah service
metadata:
  name: karsajobs-ui        # memberikan nama service
  labels:
    app: karsajobs-ui
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31767
  selector:
    app: karsajobs-ui
